[package]
name = "sequence"
version = "0.1.0"
authors = ["MaratWorker <maratn566ek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log="*"
